"""empty message

Revision ID: b4d13ea26674
Revises: 
Create Date: 2022-06-24 21:19:29.995473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d13ea26674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('filename', sa.String(length=1000), nullable=True))
    op.drop_column('note', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('path', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('note', 'filename')
    # ### end Alembic commands ###
